/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated.usuarios'
import { Route as AuthenticatedPayablesRouteImport } from './routes/_authenticated.payables'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated.fornecedores'
import { Route as AuthenticatedFilaRouteImport } from './routes/_authenticated.fila'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated.despesas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated.crm'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated.audit'
import { Route as BSlugIndexRouteImport } from './routes/b.$slug.index'
import { Route as AuthenticatedPromocoesIndexRouteImport } from './routes/_authenticated.promocoes.index'
import { Route as AuthenticatedProfissionaisIndexRouteImport } from './routes/_authenticated.profissionais.index'
import { Route as AuthenticatedPagamentosIndexRouteImport } from './routes/_authenticated.pagamentos.index'
import { Route as AuthenticatedPacotesIndexRouteImport } from './routes/_authenticated.pacotes.index'
import { Route as AuthenticatedNpsIndexRouteImport } from './routes/_authenticated.nps.index'
import { Route as AuthenticatedEstoqueIndexRouteImport } from './routes/_authenticated.estoque.index'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated.configuracoes.index'
import { Route as AuthenticatedComunicacaoIndexRouteImport } from './routes/_authenticated.comunicacao.index'
import { Route as AuthenticatedComissoesIndexRouteImport } from './routes/_authenticated.comissoes.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated.clientes.index'
import { Route as AuthenticatedAssinaturasIndexRouteImport } from './routes/_authenticated.assinaturas.index'
import { Route as AuthenticatedAgendaIndexRouteImport } from './routes/_authenticated.agenda.index'
import { Route as NpsRespondSurveyIdRouteImport } from './routes/nps.respond.$surveyId'
import { Route as BSlugAgendarRouteImport } from './routes/b.$slug.agendar'
import { Route as AuthenticatedProfissionaisIdRouteImport } from './routes/_authenticated.profissionais.$id'
import { Route as AuthenticatedPagamentosNovoRouteImport } from './routes/_authenticated.pagamentos.novo'
import { Route as AuthenticatedPagamentosIdRouteImport } from './routes/_authenticated.pagamentos.$id'
import { Route as AuthenticatedPacotesComprasRouteImport } from './routes/_authenticated.pacotes.compras'
import { Route as AuthenticatedOperacoesIdRouteImport } from './routes/_authenticated.operacoes.$id'
import { Route as AuthenticatedNpsConfigRouteImport } from './routes/_authenticated.nps.config'
import { Route as AuthenticatedFinanceiroExtratoRouteImport } from './routes/_authenticated.financeiro.extrato'
import { Route as AuthenticatedFinanceiroDreRouteImport } from './routes/_authenticated.financeiro.dre'
import { Route as AuthenticatedFinanceiroContasRouteImport } from './routes/_authenticated.financeiro.contas'
import { Route as AuthenticatedFinanceiroConciliacaoRouteImport } from './routes/_authenticated.financeiro.conciliacao'
import { Route as AuthenticatedEstoqueMovimentacoesRouteImport } from './routes/_authenticated.estoque.movimentacoes'
import { Route as AuthenticatedConfiguracoesTaxasRouteImport } from './routes/_authenticated.configuracoes.taxas'
import { Route as AuthenticatedConfiguracoesPerfilRouteImport } from './routes/_authenticated.configuracoes.perfil'
import { Route as AuthenticatedConfiguracoesModulosRouteImport } from './routes/_authenticated.configuracoes.modulos'
import { Route as AuthenticatedConfiguracoesIntegracoesRouteImport } from './routes/_authenticated.configuracoes.integracoes'
import { Route as AuthenticatedConfiguracoesFinanceiroRouteImport } from './routes/_authenticated.configuracoes.financeiro'
import { Route as AuthenticatedConfiguracoesBrandingRouteImport } from './routes/_authenticated.configuracoes.branding'
import { Route as AuthenticatedComunicacaoLogsRouteImport } from './routes/_authenticated.comunicacao.logs'
import { Route as AuthenticatedComissoesRegrasRouteImport } from './routes/_authenticated.comissoes.regras'
import { Route as AuthenticatedComissoesPagamentosRouteImport } from './routes/_authenticated.comissoes.pagamentos'
import { Route as AuthenticatedComissoesHistoricoRouteImport } from './routes/_authenticated.comissoes.historico'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated.clientes.$id'
import { Route as AuthenticatedCatalogoServicosRouteImport } from './routes/_authenticated.catalogo.servicos'
import { Route as AuthenticatedCatalogoProdutosRouteImport } from './routes/_authenticated.catalogo.produtos'
import { Route as AuthenticatedCatalogoCategoriasRouteImport } from './routes/_authenticated.catalogo.categorias'
import { Route as AuthenticatedAssinaturasPlanosRouteImport } from './routes/_authenticated.assinaturas.planos'
import { Route as AuthenticatedAgendaNovoRouteImport } from './routes/_authenticated.agenda.novo'
import { Route as BSlugConfirmacaoIdRouteImport } from './routes/b.$slug.confirmacao.$id'
import { Route as AuthenticatedPromocoesIdCuponsRouteImport } from './routes/_authenticated.promocoes.$id.cupons'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayablesRoute = AuthenticatedPayablesRouteImport.update({
  id: '/payables',
  path: '/payables',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilaRoute = AuthenticatedFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const BSlugIndexRoute = BSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BSlugRoute,
} as any)
const AuthenticatedPromocoesIndexRoute =
  AuthenticatedPromocoesIndexRouteImport.update({
    id: '/promocoes/',
    path: '/promocoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfissionaisIndexRoute =
  AuthenticatedProfissionaisIndexRouteImport.update({
    id: '/profissionais/',
    path: '/profissionais/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPagamentosIndexRoute =
  AuthenticatedPagamentosIndexRouteImport.update({
    id: '/pagamentos/',
    path: '/pagamentos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPacotesIndexRoute =
  AuthenticatedPacotesIndexRouteImport.update({
    id: '/pacotes/',
    path: '/pacotes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNpsIndexRoute = AuthenticatedNpsIndexRouteImport.update({
  id: '/nps/',
  path: '/nps/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstoqueIndexRoute =
  AuthenticatedEstoqueIndexRouteImport.update({
    id: '/estoque/',
    path: '/estoque/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComunicacaoIndexRoute =
  AuthenticatedComunicacaoIndexRouteImport.update({
    id: '/comunicacao/',
    path: '/comunicacao/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComissoesIndexRoute =
  AuthenticatedComissoesIndexRouteImport.update({
    id: '/comissoes/',
    path: '/comissoes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssinaturasIndexRoute =
  AuthenticatedAssinaturasIndexRouteImport.update({
    id: '/assinaturas/',
    path: '/assinaturas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendaIndexRoute =
  AuthenticatedAgendaIndexRouteImport.update({
    id: '/agenda/',
    path: '/agenda/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const NpsRespondSurveyIdRoute = NpsRespondSurveyIdRouteImport.update({
  id: '/nps/respond/$surveyId',
  path: '/nps/respond/$surveyId',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugAgendarRoute = BSlugAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => BSlugRoute,
} as any)
const AuthenticatedProfissionaisIdRoute =
  AuthenticatedProfissionaisIdRouteImport.update({
    id: '/profissionais/$id',
    path: '/profissionais/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPagamentosNovoRoute =
  AuthenticatedPagamentosNovoRouteImport.update({
    id: '/pagamentos/novo',
    path: '/pagamentos/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPagamentosIdRoute =
  AuthenticatedPagamentosIdRouteImport.update({
    id: '/pagamentos/$id',
    path: '/pagamentos/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPacotesComprasRoute =
  AuthenticatedPacotesComprasRouteImport.update({
    id: '/pacotes/compras',
    path: '/pacotes/compras',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperacoesIdRoute =
  AuthenticatedOperacoesIdRouteImport.update({
    id: '/operacoes/$id',
    path: '/operacoes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNpsConfigRoute = AuthenticatedNpsConfigRouteImport.update({
  id: '/nps/config',
  path: '/nps/config',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroExtratoRoute =
  AuthenticatedFinanceiroExtratoRouteImport.update({
    id: '/financeiro/extrato',
    path: '/financeiro/extrato',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroDreRoute =
  AuthenticatedFinanceiroDreRouteImport.update({
    id: '/financeiro/dre',
    path: '/financeiro/dre',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroContasRoute =
  AuthenticatedFinanceiroContasRouteImport.update({
    id: '/financeiro/contas',
    path: '/financeiro/contas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroConciliacaoRoute =
  AuthenticatedFinanceiroConciliacaoRouteImport.update({
    id: '/financeiro/conciliacao',
    path: '/financeiro/conciliacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEstoqueMovimentacoesRoute =
  AuthenticatedEstoqueMovimentacoesRouteImport.update({
    id: '/estoque/movimentacoes',
    path: '/estoque/movimentacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesTaxasRoute =
  AuthenticatedConfiguracoesTaxasRouteImport.update({
    id: '/configuracoes/taxas',
    path: '/configuracoes/taxas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesPerfilRoute =
  AuthenticatedConfiguracoesPerfilRouteImport.update({
    id: '/configuracoes/perfil',
    path: '/configuracoes/perfil',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesModulosRoute =
  AuthenticatedConfiguracoesModulosRouteImport.update({
    id: '/configuracoes/modulos',
    path: '/configuracoes/modulos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesIntegracoesRoute =
  AuthenticatedConfiguracoesIntegracoesRouteImport.update({
    id: '/configuracoes/integracoes',
    path: '/configuracoes/integracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesFinanceiroRoute =
  AuthenticatedConfiguracoesFinanceiroRouteImport.update({
    id: '/configuracoes/financeiro',
    path: '/configuracoes/financeiro',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesBrandingRoute =
  AuthenticatedConfiguracoesBrandingRouteImport.update({
    id: '/configuracoes/branding',
    path: '/configuracoes/branding',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComunicacaoLogsRoute =
  AuthenticatedComunicacaoLogsRouteImport.update({
    id: '/comunicacao/logs',
    path: '/comunicacao/logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComissoesRegrasRoute =
  AuthenticatedComissoesRegrasRouteImport.update({
    id: '/comissoes/regras',
    path: '/comissoes/regras',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComissoesPagamentosRoute =
  AuthenticatedComissoesPagamentosRouteImport.update({
    id: '/comissoes/pagamentos',
    path: '/comissoes/pagamentos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComissoesHistoricoRoute =
  AuthenticatedComissoesHistoricoRouteImport.update({
    id: '/comissoes/historico',
    path: '/comissoes/historico',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogoServicosRoute =
  AuthenticatedCatalogoServicosRouteImport.update({
    id: '/catalogo/servicos',
    path: '/catalogo/servicos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogoProdutosRoute =
  AuthenticatedCatalogoProdutosRouteImport.update({
    id: '/catalogo/produtos',
    path: '/catalogo/produtos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogoCategoriasRoute =
  AuthenticatedCatalogoCategoriasRouteImport.update({
    id: '/catalogo/categorias',
    path: '/catalogo/categorias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssinaturasPlanosRoute =
  AuthenticatedAssinaturasPlanosRouteImport.update({
    id: '/assinaturas/planos',
    path: '/assinaturas/planos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgendaNovoRoute = AuthenticatedAgendaNovoRouteImport.update({
  id: '/agenda/novo',
  path: '/agenda/novo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const BSlugConfirmacaoIdRoute = BSlugConfirmacaoIdRouteImport.update({
  id: '/confirmacao/$id',
  path: '/confirmacao/$id',
  getParentRoute: () => BSlugRoute,
} as any)
const AuthenticatedPromocoesIdCuponsRoute =
  AuthenticatedPromocoesIdCuponsRouteImport.update({
    id: '/promocoes/$id/cupons',
    path: '/promocoes/$id/cupons',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/audit': typeof AuthenticatedAuditRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/payables': typeof AuthenticatedPayablesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/owner/': typeof OwnerIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/agenda/novo': typeof AuthenticatedAgendaNovoRoute
  '/assinaturas/planos': typeof AuthenticatedAssinaturasPlanosRoute
  '/catalogo/categorias': typeof AuthenticatedCatalogoCategoriasRoute
  '/catalogo/produtos': typeof AuthenticatedCatalogoProdutosRoute
  '/catalogo/servicos': typeof AuthenticatedCatalogoServicosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/comissoes/historico': typeof AuthenticatedComissoesHistoricoRoute
  '/comissoes/pagamentos': typeof AuthenticatedComissoesPagamentosRoute
  '/comissoes/regras': typeof AuthenticatedComissoesRegrasRoute
  '/comunicacao/logs': typeof AuthenticatedComunicacaoLogsRoute
  '/configuracoes/branding': typeof AuthenticatedConfiguracoesBrandingRoute
  '/configuracoes/financeiro': typeof AuthenticatedConfiguracoesFinanceiroRoute
  '/configuracoes/integracoes': typeof AuthenticatedConfiguracoesIntegracoesRoute
  '/configuracoes/modulos': typeof AuthenticatedConfiguracoesModulosRoute
  '/configuracoes/perfil': typeof AuthenticatedConfiguracoesPerfilRoute
  '/configuracoes/taxas': typeof AuthenticatedConfiguracoesTaxasRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/contas': typeof AuthenticatedFinanceiroContasRoute
  '/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/financeiro/extrato': typeof AuthenticatedFinanceiroExtratoRoute
  '/nps/config': typeof AuthenticatedNpsConfigRoute
  '/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
  '/pacotes/compras': typeof AuthenticatedPacotesComprasRoute
  '/pagamentos/$id': typeof AuthenticatedPagamentosIdRoute
  '/pagamentos/novo': typeof AuthenticatedPagamentosNovoRoute
  '/profissionais/$id': typeof AuthenticatedProfissionaisIdRoute
  '/b/$slug/agendar': typeof BSlugAgendarRoute
  '/nps/respond/$surveyId': typeof NpsRespondSurveyIdRoute
  '/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/assinaturas/': typeof AuthenticatedAssinaturasIndexRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/comissoes/': typeof AuthenticatedComissoesIndexRoute
  '/comunicacao/': typeof AuthenticatedComunicacaoIndexRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/nps/': typeof AuthenticatedNpsIndexRoute
  '/pacotes/': typeof AuthenticatedPacotesIndexRoute
  '/pagamentos/': typeof AuthenticatedPagamentosIndexRoute
  '/profissionais/': typeof AuthenticatedProfissionaisIndexRoute
  '/promocoes/': typeof AuthenticatedPromocoesIndexRoute
  '/b/$slug/': typeof BSlugIndexRoute
  '/promocoes/$id/cupons': typeof AuthenticatedPromocoesIdCuponsRoute
  '/b/$slug/confirmacao/$id': typeof BSlugConfirmacaoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/payables': typeof AuthenticatedPayablesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/owner': typeof OwnerIndexRoute
  '/portal': typeof PortalIndexRoute
  '/agenda/novo': typeof AuthenticatedAgendaNovoRoute
  '/assinaturas/planos': typeof AuthenticatedAssinaturasPlanosRoute
  '/catalogo/categorias': typeof AuthenticatedCatalogoCategoriasRoute
  '/catalogo/produtos': typeof AuthenticatedCatalogoProdutosRoute
  '/catalogo/servicos': typeof AuthenticatedCatalogoServicosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/comissoes/historico': typeof AuthenticatedComissoesHistoricoRoute
  '/comissoes/pagamentos': typeof AuthenticatedComissoesPagamentosRoute
  '/comissoes/regras': typeof AuthenticatedComissoesRegrasRoute
  '/comunicacao/logs': typeof AuthenticatedComunicacaoLogsRoute
  '/configuracoes/branding': typeof AuthenticatedConfiguracoesBrandingRoute
  '/configuracoes/financeiro': typeof AuthenticatedConfiguracoesFinanceiroRoute
  '/configuracoes/integracoes': typeof AuthenticatedConfiguracoesIntegracoesRoute
  '/configuracoes/modulos': typeof AuthenticatedConfiguracoesModulosRoute
  '/configuracoes/perfil': typeof AuthenticatedConfiguracoesPerfilRoute
  '/configuracoes/taxas': typeof AuthenticatedConfiguracoesTaxasRoute
  '/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/contas': typeof AuthenticatedFinanceiroContasRoute
  '/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/financeiro/extrato': typeof AuthenticatedFinanceiroExtratoRoute
  '/nps/config': typeof AuthenticatedNpsConfigRoute
  '/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
  '/pacotes/compras': typeof AuthenticatedPacotesComprasRoute
  '/pagamentos/$id': typeof AuthenticatedPagamentosIdRoute
  '/pagamentos/novo': typeof AuthenticatedPagamentosNovoRoute
  '/profissionais/$id': typeof AuthenticatedProfissionaisIdRoute
  '/b/$slug/agendar': typeof BSlugAgendarRoute
  '/nps/respond/$surveyId': typeof NpsRespondSurveyIdRoute
  '/agenda': typeof AuthenticatedAgendaIndexRoute
  '/assinaturas': typeof AuthenticatedAssinaturasIndexRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/comissoes': typeof AuthenticatedComissoesIndexRoute
  '/comunicacao': typeof AuthenticatedComunicacaoIndexRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/estoque': typeof AuthenticatedEstoqueIndexRoute
  '/nps': typeof AuthenticatedNpsIndexRoute
  '/pacotes': typeof AuthenticatedPacotesIndexRoute
  '/pagamentos': typeof AuthenticatedPagamentosIndexRoute
  '/profissionais': typeof AuthenticatedProfissionaisIndexRoute
  '/promocoes': typeof AuthenticatedPromocoesIndexRoute
  '/b/$slug': typeof BSlugIndexRoute
  '/promocoes/$id/cupons': typeof AuthenticatedPromocoesIdCuponsRoute
  '/b/$slug/confirmacao/$id': typeof BSlugConfirmacaoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/fila': typeof AuthenticatedFilaRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/payables': typeof AuthenticatedPayablesRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/b/$slug': typeof BSlugRouteWithChildren
  '/owner/': typeof OwnerIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/agenda/novo': typeof AuthenticatedAgendaNovoRoute
  '/_authenticated/assinaturas/planos': typeof AuthenticatedAssinaturasPlanosRoute
  '/_authenticated/catalogo/categorias': typeof AuthenticatedCatalogoCategoriasRoute
  '/_authenticated/catalogo/produtos': typeof AuthenticatedCatalogoProdutosRoute
  '/_authenticated/catalogo/servicos': typeof AuthenticatedCatalogoServicosRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/comissoes/historico': typeof AuthenticatedComissoesHistoricoRoute
  '/_authenticated/comissoes/pagamentos': typeof AuthenticatedComissoesPagamentosRoute
  '/_authenticated/comissoes/regras': typeof AuthenticatedComissoesRegrasRoute
  '/_authenticated/comunicacao/logs': typeof AuthenticatedComunicacaoLogsRoute
  '/_authenticated/configuracoes/branding': typeof AuthenticatedConfiguracoesBrandingRoute
  '/_authenticated/configuracoes/financeiro': typeof AuthenticatedConfiguracoesFinanceiroRoute
  '/_authenticated/configuracoes/integracoes': typeof AuthenticatedConfiguracoesIntegracoesRoute
  '/_authenticated/configuracoes/modulos': typeof AuthenticatedConfiguracoesModulosRoute
  '/_authenticated/configuracoes/perfil': typeof AuthenticatedConfiguracoesPerfilRoute
  '/_authenticated/configuracoes/taxas': typeof AuthenticatedConfiguracoesTaxasRoute
  '/_authenticated/estoque/movimentacoes': typeof AuthenticatedEstoqueMovimentacoesRoute
  '/_authenticated/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/_authenticated/financeiro/contas': typeof AuthenticatedFinanceiroContasRoute
  '/_authenticated/financeiro/dre': typeof AuthenticatedFinanceiroDreRoute
  '/_authenticated/financeiro/extrato': typeof AuthenticatedFinanceiroExtratoRoute
  '/_authenticated/nps/config': typeof AuthenticatedNpsConfigRoute
  '/_authenticated/operacoes/$id': typeof AuthenticatedOperacoesIdRoute
  '/_authenticated/pacotes/compras': typeof AuthenticatedPacotesComprasRoute
  '/_authenticated/pagamentos/$id': typeof AuthenticatedPagamentosIdRoute
  '/_authenticated/pagamentos/novo': typeof AuthenticatedPagamentosNovoRoute
  '/_authenticated/profissionais/$id': typeof AuthenticatedProfissionaisIdRoute
  '/b/$slug/agendar': typeof BSlugAgendarRoute
  '/nps/respond/$surveyId': typeof NpsRespondSurveyIdRoute
  '/_authenticated/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/_authenticated/assinaturas/': typeof AuthenticatedAssinaturasIndexRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/comissoes/': typeof AuthenticatedComissoesIndexRoute
  '/_authenticated/comunicacao/': typeof AuthenticatedComunicacaoIndexRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/_authenticated/nps/': typeof AuthenticatedNpsIndexRoute
  '/_authenticated/pacotes/': typeof AuthenticatedPacotesIndexRoute
  '/_authenticated/pagamentos/': typeof AuthenticatedPagamentosIndexRoute
  '/_authenticated/profissionais/': typeof AuthenticatedProfissionaisIndexRoute
  '/_authenticated/promocoes/': typeof AuthenticatedPromocoesIndexRoute
  '/b/$slug/': typeof BSlugIndexRoute
  '/_authenticated/promocoes/$id/cupons': typeof AuthenticatedPromocoesIdCuponsRoute
  '/b/$slug/confirmacao/$id': typeof BSlugConfirmacaoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/owner'
    | '/portal'
    | '/audit'
    | '/crm'
    | '/dashboard'
    | '/despesas'
    | '/fila'
    | '/fornecedores'
    | '/inbox'
    | '/payables'
    | '/usuarios'
    | '/b/$slug'
    | '/owner/'
    | '/portal/'
    | '/agenda/novo'
    | '/assinaturas/planos'
    | '/catalogo/categorias'
    | '/catalogo/produtos'
    | '/catalogo/servicos'
    | '/clientes/$id'
    | '/comissoes/historico'
    | '/comissoes/pagamentos'
    | '/comissoes/regras'
    | '/comunicacao/logs'
    | '/configuracoes/branding'
    | '/configuracoes/financeiro'
    | '/configuracoes/integracoes'
    | '/configuracoes/modulos'
    | '/configuracoes/perfil'
    | '/configuracoes/taxas'
    | '/estoque/movimentacoes'
    | '/financeiro/conciliacao'
    | '/financeiro/contas'
    | '/financeiro/dre'
    | '/financeiro/extrato'
    | '/nps/config'
    | '/operacoes/$id'
    | '/pacotes/compras'
    | '/pagamentos/$id'
    | '/pagamentos/novo'
    | '/profissionais/$id'
    | '/b/$slug/agendar'
    | '/nps/respond/$surveyId'
    | '/agenda/'
    | '/assinaturas/'
    | '/clientes/'
    | '/comissoes/'
    | '/comunicacao/'
    | '/configuracoes/'
    | '/estoque/'
    | '/nps/'
    | '/pacotes/'
    | '/pagamentos/'
    | '/profissionais/'
    | '/promocoes/'
    | '/b/$slug/'
    | '/promocoes/$id/cupons'
    | '/b/$slug/confirmacao/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit'
    | '/crm'
    | '/dashboard'
    | '/despesas'
    | '/fila'
    | '/fornecedores'
    | '/inbox'
    | '/payables'
    | '/usuarios'
    | '/owner'
    | '/portal'
    | '/agenda/novo'
    | '/assinaturas/planos'
    | '/catalogo/categorias'
    | '/catalogo/produtos'
    | '/catalogo/servicos'
    | '/clientes/$id'
    | '/comissoes/historico'
    | '/comissoes/pagamentos'
    | '/comissoes/regras'
    | '/comunicacao/logs'
    | '/configuracoes/branding'
    | '/configuracoes/financeiro'
    | '/configuracoes/integracoes'
    | '/configuracoes/modulos'
    | '/configuracoes/perfil'
    | '/configuracoes/taxas'
    | '/estoque/movimentacoes'
    | '/financeiro/conciliacao'
    | '/financeiro/contas'
    | '/financeiro/dre'
    | '/financeiro/extrato'
    | '/nps/config'
    | '/operacoes/$id'
    | '/pacotes/compras'
    | '/pagamentos/$id'
    | '/pagamentos/novo'
    | '/profissionais/$id'
    | '/b/$slug/agendar'
    | '/nps/respond/$surveyId'
    | '/agenda'
    | '/assinaturas'
    | '/clientes'
    | '/comissoes'
    | '/comunicacao'
    | '/configuracoes'
    | '/estoque'
    | '/nps'
    | '/pacotes'
    | '/pagamentos'
    | '/profissionais'
    | '/promocoes'
    | '/b/$slug'
    | '/promocoes/$id/cupons'
    | '/b/$slug/confirmacao/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/owner'
    | '/portal'
    | '/_authenticated/audit'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/despesas'
    | '/_authenticated/fila'
    | '/_authenticated/fornecedores'
    | '/_authenticated/inbox'
    | '/_authenticated/payables'
    | '/_authenticated/usuarios'
    | '/b/$slug'
    | '/owner/'
    | '/portal/'
    | '/_authenticated/agenda/novo'
    | '/_authenticated/assinaturas/planos'
    | '/_authenticated/catalogo/categorias'
    | '/_authenticated/catalogo/produtos'
    | '/_authenticated/catalogo/servicos'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/comissoes/historico'
    | '/_authenticated/comissoes/pagamentos'
    | '/_authenticated/comissoes/regras'
    | '/_authenticated/comunicacao/logs'
    | '/_authenticated/configuracoes/branding'
    | '/_authenticated/configuracoes/financeiro'
    | '/_authenticated/configuracoes/integracoes'
    | '/_authenticated/configuracoes/modulos'
    | '/_authenticated/configuracoes/perfil'
    | '/_authenticated/configuracoes/taxas'
    | '/_authenticated/estoque/movimentacoes'
    | '/_authenticated/financeiro/conciliacao'
    | '/_authenticated/financeiro/contas'
    | '/_authenticated/financeiro/dre'
    | '/_authenticated/financeiro/extrato'
    | '/_authenticated/nps/config'
    | '/_authenticated/operacoes/$id'
    | '/_authenticated/pacotes/compras'
    | '/_authenticated/pagamentos/$id'
    | '/_authenticated/pagamentos/novo'
    | '/_authenticated/profissionais/$id'
    | '/b/$slug/agendar'
    | '/nps/respond/$surveyId'
    | '/_authenticated/agenda/'
    | '/_authenticated/assinaturas/'
    | '/_authenticated/clientes/'
    | '/_authenticated/comissoes/'
    | '/_authenticated/comunicacao/'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/estoque/'
    | '/_authenticated/nps/'
    | '/_authenticated/pacotes/'
    | '/_authenticated/pagamentos/'
    | '/_authenticated/profissionais/'
    | '/_authenticated/promocoes/'
    | '/b/$slug/'
    | '/_authenticated/promocoes/$id/cupons'
    | '/b/$slug/confirmacao/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  BSlugRoute: typeof BSlugRouteWithChildren
  NpsRespondSurveyIdRoute: typeof NpsRespondSurveyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payables': {
      id: '/_authenticated/payables'
      path: '/payables'
      fullPath: '/payables'
      preLoaderRoute: typeof AuthenticatedPayablesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fila': {
      id: '/_authenticated/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof AuthenticatedFilaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/b/$slug/': {
      id: '/b/$slug/'
      path: '/'
      fullPath: '/b/$slug/'
      preLoaderRoute: typeof BSlugIndexRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/_authenticated/promocoes/': {
      id: '/_authenticated/promocoes/'
      path: '/promocoes'
      fullPath: '/promocoes/'
      preLoaderRoute: typeof AuthenticatedPromocoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profissionais/': {
      id: '/_authenticated/profissionais/'
      path: '/profissionais'
      fullPath: '/profissionais/'
      preLoaderRoute: typeof AuthenticatedProfissionaisIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pagamentos/': {
      id: '/_authenticated/pagamentos/'
      path: '/pagamentos'
      fullPath: '/pagamentos/'
      preLoaderRoute: typeof AuthenticatedPagamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacotes/': {
      id: '/_authenticated/pacotes/'
      path: '/pacotes'
      fullPath: '/pacotes/'
      preLoaderRoute: typeof AuthenticatedPacotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nps/': {
      id: '/_authenticated/nps/'
      path: '/nps'
      fullPath: '/nps/'
      preLoaderRoute: typeof AuthenticatedNpsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque/': {
      id: '/_authenticated/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AuthenticatedEstoqueIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comunicacao/': {
      id: '/_authenticated/comunicacao/'
      path: '/comunicacao'
      fullPath: '/comunicacao/'
      preLoaderRoute: typeof AuthenticatedComunicacaoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comissoes/': {
      id: '/_authenticated/comissoes/'
      path: '/comissoes'
      fullPath: '/comissoes/'
      preLoaderRoute: typeof AuthenticatedComissoesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinaturas/': {
      id: '/_authenticated/assinaturas/'
      path: '/assinaturas'
      fullPath: '/assinaturas/'
      preLoaderRoute: typeof AuthenticatedAssinaturasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda/': {
      id: '/_authenticated/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AuthenticatedAgendaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/nps/respond/$surveyId': {
      id: '/nps/respond/$surveyId'
      path: '/nps/respond/$surveyId'
      fullPath: '/nps/respond/$surveyId'
      preLoaderRoute: typeof NpsRespondSurveyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug/agendar': {
      id: '/b/$slug/agendar'
      path: '/agendar'
      fullPath: '/b/$slug/agendar'
      preLoaderRoute: typeof BSlugAgendarRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/_authenticated/profissionais/$id': {
      id: '/_authenticated/profissionais/$id'
      path: '/profissionais/$id'
      fullPath: '/profissionais/$id'
      preLoaderRoute: typeof AuthenticatedProfissionaisIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pagamentos/novo': {
      id: '/_authenticated/pagamentos/novo'
      path: '/pagamentos/novo'
      fullPath: '/pagamentos/novo'
      preLoaderRoute: typeof AuthenticatedPagamentosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pagamentos/$id': {
      id: '/_authenticated/pagamentos/$id'
      path: '/pagamentos/$id'
      fullPath: '/pagamentos/$id'
      preLoaderRoute: typeof AuthenticatedPagamentosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacotes/compras': {
      id: '/_authenticated/pacotes/compras'
      path: '/pacotes/compras'
      fullPath: '/pacotes/compras'
      preLoaderRoute: typeof AuthenticatedPacotesComprasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operacoes/$id': {
      id: '/_authenticated/operacoes/$id'
      path: '/operacoes/$id'
      fullPath: '/operacoes/$id'
      preLoaderRoute: typeof AuthenticatedOperacoesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nps/config': {
      id: '/_authenticated/nps/config'
      path: '/nps/config'
      fullPath: '/nps/config'
      preLoaderRoute: typeof AuthenticatedNpsConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/extrato': {
      id: '/_authenticated/financeiro/extrato'
      path: '/financeiro/extrato'
      fullPath: '/financeiro/extrato'
      preLoaderRoute: typeof AuthenticatedFinanceiroExtratoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/dre': {
      id: '/_authenticated/financeiro/dre'
      path: '/financeiro/dre'
      fullPath: '/financeiro/dre'
      preLoaderRoute: typeof AuthenticatedFinanceiroDreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/contas': {
      id: '/_authenticated/financeiro/contas'
      path: '/financeiro/contas'
      fullPath: '/financeiro/contas'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro/conciliacao': {
      id: '/_authenticated/financeiro/conciliacao'
      path: '/financeiro/conciliacao'
      fullPath: '/financeiro/conciliacao'
      preLoaderRoute: typeof AuthenticatedFinanceiroConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estoque/movimentacoes': {
      id: '/_authenticated/estoque/movimentacoes'
      path: '/estoque/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof AuthenticatedEstoqueMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/taxas': {
      id: '/_authenticated/configuracoes/taxas'
      path: '/configuracoes/taxas'
      fullPath: '/configuracoes/taxas'
      preLoaderRoute: typeof AuthenticatedConfiguracoesTaxasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/perfil': {
      id: '/_authenticated/configuracoes/perfil'
      path: '/configuracoes/perfil'
      fullPath: '/configuracoes/perfil'
      preLoaderRoute: typeof AuthenticatedConfiguracoesPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/modulos': {
      id: '/_authenticated/configuracoes/modulos'
      path: '/configuracoes/modulos'
      fullPath: '/configuracoes/modulos'
      preLoaderRoute: typeof AuthenticatedConfiguracoesModulosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/integracoes': {
      id: '/_authenticated/configuracoes/integracoes'
      path: '/configuracoes/integracoes'
      fullPath: '/configuracoes/integracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/financeiro': {
      id: '/_authenticated/configuracoes/financeiro'
      path: '/configuracoes/financeiro'
      fullPath: '/configuracoes/financeiro'
      preLoaderRoute: typeof AuthenticatedConfiguracoesFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes/branding': {
      id: '/_authenticated/configuracoes/branding'
      path: '/configuracoes/branding'
      fullPath: '/configuracoes/branding'
      preLoaderRoute: typeof AuthenticatedConfiguracoesBrandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comunicacao/logs': {
      id: '/_authenticated/comunicacao/logs'
      path: '/comunicacao/logs'
      fullPath: '/comunicacao/logs'
      preLoaderRoute: typeof AuthenticatedComunicacaoLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comissoes/regras': {
      id: '/_authenticated/comissoes/regras'
      path: '/comissoes/regras'
      fullPath: '/comissoes/regras'
      preLoaderRoute: typeof AuthenticatedComissoesRegrasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comissoes/pagamentos': {
      id: '/_authenticated/comissoes/pagamentos'
      path: '/comissoes/pagamentos'
      fullPath: '/comissoes/pagamentos'
      preLoaderRoute: typeof AuthenticatedComissoesPagamentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comissoes/historico': {
      id: '/_authenticated/comissoes/historico'
      path: '/comissoes/historico'
      fullPath: '/comissoes/historico'
      preLoaderRoute: typeof AuthenticatedComissoesHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogo/servicos': {
      id: '/_authenticated/catalogo/servicos'
      path: '/catalogo/servicos'
      fullPath: '/catalogo/servicos'
      preLoaderRoute: typeof AuthenticatedCatalogoServicosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogo/produtos': {
      id: '/_authenticated/catalogo/produtos'
      path: '/catalogo/produtos'
      fullPath: '/catalogo/produtos'
      preLoaderRoute: typeof AuthenticatedCatalogoProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalogo/categorias': {
      id: '/_authenticated/catalogo/categorias'
      path: '/catalogo/categorias'
      fullPath: '/catalogo/categorias'
      preLoaderRoute: typeof AuthenticatedCatalogoCategoriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinaturas/planos': {
      id: '/_authenticated/assinaturas/planos'
      path: '/assinaturas/planos'
      fullPath: '/assinaturas/planos'
      preLoaderRoute: typeof AuthenticatedAssinaturasPlanosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda/novo': {
      id: '/_authenticated/agenda/novo'
      path: '/agenda/novo'
      fullPath: '/agenda/novo'
      preLoaderRoute: typeof AuthenticatedAgendaNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/b/$slug/confirmacao/$id': {
      id: '/b/$slug/confirmacao/$id'
      path: '/confirmacao/$id'
      fullPath: '/b/$slug/confirmacao/$id'
      preLoaderRoute: typeof BSlugConfirmacaoIdRouteImport
      parentRoute: typeof BSlugRoute
    }
    '/_authenticated/promocoes/$id/cupons': {
      id: '/_authenticated/promocoes/$id/cupons'
      path: '/promocoes/$id/cupons'
      fullPath: '/promocoes/$id/cupons'
      preLoaderRoute: typeof AuthenticatedPromocoesIdCuponsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedFilaRoute: typeof AuthenticatedFilaRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedPayablesRoute: typeof AuthenticatedPayablesRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedAgendaNovoRoute: typeof AuthenticatedAgendaNovoRoute
  AuthenticatedAssinaturasPlanosRoute: typeof AuthenticatedAssinaturasPlanosRoute
  AuthenticatedCatalogoCategoriasRoute: typeof AuthenticatedCatalogoCategoriasRoute
  AuthenticatedCatalogoProdutosRoute: typeof AuthenticatedCatalogoProdutosRoute
  AuthenticatedCatalogoServicosRoute: typeof AuthenticatedCatalogoServicosRoute
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedComissoesHistoricoRoute: typeof AuthenticatedComissoesHistoricoRoute
  AuthenticatedComissoesPagamentosRoute: typeof AuthenticatedComissoesPagamentosRoute
  AuthenticatedComissoesRegrasRoute: typeof AuthenticatedComissoesRegrasRoute
  AuthenticatedComunicacaoLogsRoute: typeof AuthenticatedComunicacaoLogsRoute
  AuthenticatedConfiguracoesBrandingRoute: typeof AuthenticatedConfiguracoesBrandingRoute
  AuthenticatedConfiguracoesFinanceiroRoute: typeof AuthenticatedConfiguracoesFinanceiroRoute
  AuthenticatedConfiguracoesIntegracoesRoute: typeof AuthenticatedConfiguracoesIntegracoesRoute
  AuthenticatedConfiguracoesModulosRoute: typeof AuthenticatedConfiguracoesModulosRoute
  AuthenticatedConfiguracoesPerfilRoute: typeof AuthenticatedConfiguracoesPerfilRoute
  AuthenticatedConfiguracoesTaxasRoute: typeof AuthenticatedConfiguracoesTaxasRoute
  AuthenticatedEstoqueMovimentacoesRoute: typeof AuthenticatedEstoqueMovimentacoesRoute
  AuthenticatedFinanceiroConciliacaoRoute: typeof AuthenticatedFinanceiroConciliacaoRoute
  AuthenticatedFinanceiroContasRoute: typeof AuthenticatedFinanceiroContasRoute
  AuthenticatedFinanceiroDreRoute: typeof AuthenticatedFinanceiroDreRoute
  AuthenticatedFinanceiroExtratoRoute: typeof AuthenticatedFinanceiroExtratoRoute
  AuthenticatedNpsConfigRoute: typeof AuthenticatedNpsConfigRoute
  AuthenticatedOperacoesIdRoute: typeof AuthenticatedOperacoesIdRoute
  AuthenticatedPacotesComprasRoute: typeof AuthenticatedPacotesComprasRoute
  AuthenticatedPagamentosIdRoute: typeof AuthenticatedPagamentosIdRoute
  AuthenticatedPagamentosNovoRoute: typeof AuthenticatedPagamentosNovoRoute
  AuthenticatedProfissionaisIdRoute: typeof AuthenticatedProfissionaisIdRoute
  AuthenticatedAgendaIndexRoute: typeof AuthenticatedAgendaIndexRoute
  AuthenticatedAssinaturasIndexRoute: typeof AuthenticatedAssinaturasIndexRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedComissoesIndexRoute: typeof AuthenticatedComissoesIndexRoute
  AuthenticatedComunicacaoIndexRoute: typeof AuthenticatedComunicacaoIndexRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
  AuthenticatedEstoqueIndexRoute: typeof AuthenticatedEstoqueIndexRoute
  AuthenticatedNpsIndexRoute: typeof AuthenticatedNpsIndexRoute
  AuthenticatedPacotesIndexRoute: typeof AuthenticatedPacotesIndexRoute
  AuthenticatedPagamentosIndexRoute: typeof AuthenticatedPagamentosIndexRoute
  AuthenticatedProfissionaisIndexRoute: typeof AuthenticatedProfissionaisIndexRoute
  AuthenticatedPromocoesIndexRoute: typeof AuthenticatedPromocoesIndexRoute
  AuthenticatedPromocoesIdCuponsRoute: typeof AuthenticatedPromocoesIdCuponsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedFilaRoute: AuthenticatedFilaRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedPayablesRoute: AuthenticatedPayablesRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedAgendaNovoRoute: AuthenticatedAgendaNovoRoute,
  AuthenticatedAssinaturasPlanosRoute: AuthenticatedAssinaturasPlanosRoute,
  AuthenticatedCatalogoCategoriasRoute: AuthenticatedCatalogoCategoriasRoute,
  AuthenticatedCatalogoProdutosRoute: AuthenticatedCatalogoProdutosRoute,
  AuthenticatedCatalogoServicosRoute: AuthenticatedCatalogoServicosRoute,
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedComissoesHistoricoRoute: AuthenticatedComissoesHistoricoRoute,
  AuthenticatedComissoesPagamentosRoute: AuthenticatedComissoesPagamentosRoute,
  AuthenticatedComissoesRegrasRoute: AuthenticatedComissoesRegrasRoute,
  AuthenticatedComunicacaoLogsRoute: AuthenticatedComunicacaoLogsRoute,
  AuthenticatedConfiguracoesBrandingRoute:
    AuthenticatedConfiguracoesBrandingRoute,
  AuthenticatedConfiguracoesFinanceiroRoute:
    AuthenticatedConfiguracoesFinanceiroRoute,
  AuthenticatedConfiguracoesIntegracoesRoute:
    AuthenticatedConfiguracoesIntegracoesRoute,
  AuthenticatedConfiguracoesModulosRoute:
    AuthenticatedConfiguracoesModulosRoute,
  AuthenticatedConfiguracoesPerfilRoute: AuthenticatedConfiguracoesPerfilRoute,
  AuthenticatedConfiguracoesTaxasRoute: AuthenticatedConfiguracoesTaxasRoute,
  AuthenticatedEstoqueMovimentacoesRoute:
    AuthenticatedEstoqueMovimentacoesRoute,
  AuthenticatedFinanceiroConciliacaoRoute:
    AuthenticatedFinanceiroConciliacaoRoute,
  AuthenticatedFinanceiroContasRoute: AuthenticatedFinanceiroContasRoute,
  AuthenticatedFinanceiroDreRoute: AuthenticatedFinanceiroDreRoute,
  AuthenticatedFinanceiroExtratoRoute: AuthenticatedFinanceiroExtratoRoute,
  AuthenticatedNpsConfigRoute: AuthenticatedNpsConfigRoute,
  AuthenticatedOperacoesIdRoute: AuthenticatedOperacoesIdRoute,
  AuthenticatedPacotesComprasRoute: AuthenticatedPacotesComprasRoute,
  AuthenticatedPagamentosIdRoute: AuthenticatedPagamentosIdRoute,
  AuthenticatedPagamentosNovoRoute: AuthenticatedPagamentosNovoRoute,
  AuthenticatedProfissionaisIdRoute: AuthenticatedProfissionaisIdRoute,
  AuthenticatedAgendaIndexRoute: AuthenticatedAgendaIndexRoute,
  AuthenticatedAssinaturasIndexRoute: AuthenticatedAssinaturasIndexRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedComissoesIndexRoute: AuthenticatedComissoesIndexRoute,
  AuthenticatedComunicacaoIndexRoute: AuthenticatedComunicacaoIndexRoute,
  AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  AuthenticatedEstoqueIndexRoute: AuthenticatedEstoqueIndexRoute,
  AuthenticatedNpsIndexRoute: AuthenticatedNpsIndexRoute,
  AuthenticatedPacotesIndexRoute: AuthenticatedPacotesIndexRoute,
  AuthenticatedPagamentosIndexRoute: AuthenticatedPagamentosIndexRoute,
  AuthenticatedProfissionaisIndexRoute: AuthenticatedProfissionaisIndexRoute,
  AuthenticatedPromocoesIndexRoute: AuthenticatedPromocoesIndexRoute,
  AuthenticatedPromocoesIdCuponsRoute: AuthenticatedPromocoesIdCuponsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OwnerRouteChildren {
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface PortalRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface BSlugRouteChildren {
  BSlugAgendarRoute: typeof BSlugAgendarRoute
  BSlugIndexRoute: typeof BSlugIndexRoute
  BSlugConfirmacaoIdRoute: typeof BSlugConfirmacaoIdRoute
}

const BSlugRouteChildren: BSlugRouteChildren = {
  BSlugAgendarRoute: BSlugAgendarRoute,
  BSlugIndexRoute: BSlugIndexRoute,
  BSlugConfirmacaoIdRoute: BSlugConfirmacaoIdRoute,
}

const BSlugRouteWithChildren = BSlugRoute._addFileChildren(BSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  BSlugRoute: BSlugRouteWithChildren,
  NpsRespondSurveyIdRoute: NpsRespondSurveyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
