/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BSlugRouteImport } from './routes/b.$slug'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppServicosRouteImport } from './routes/_authenticated.app.servicos'
import { Route as AuthenticatedAppFinanceiroRouteImport } from './routes/_authenticated.app.financeiro'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated.app.configuracoes'
import { Route as AuthenticatedAppClientesRouteImport } from './routes/_authenticated.app.clientes'
import { Route as AuthenticatedAppBarbeirosRouteImport } from './routes/_authenticated.app.barbeiros'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated.app.agenda'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BSlugRoute = BSlugRouteImport.update({
  id: '/b/$slug',
  path: '/b/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppServicosRoute =
  AuthenticatedAppServicosRouteImport.update({
    id: '/app/servicos',
    path: '/app/servicos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppFinanceiroRoute =
  AuthenticatedAppFinanceiroRouteImport.update({
    id: '/app/financeiro',
    path: '/app/financeiro',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/app/configuracoes',
    path: '/app/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppClientesRoute =
  AuthenticatedAppClientesRouteImport.update({
    id: '/app/clientes',
    path: '/app/clientes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppBarbeirosRoute =
  AuthenticatedAppBarbeirosRouteImport.update({
    id: '/app/barbeiros',
    path: '/app/barbeiros',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/app/agenda',
  path: '/app/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/b/$slug': typeof BSlugRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/barbeiros': typeof AuthenticatedAppBarbeirosRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/servicos': typeof AuthenticatedAppServicosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/b/$slug': typeof BSlugRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/barbeiros': typeof AuthenticatedAppBarbeirosRoute
  '/app/clientes': typeof AuthenticatedAppClientesRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/app/servicos': typeof AuthenticatedAppServicosRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/b/$slug': typeof BSlugRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/barbeiros': typeof AuthenticatedAppBarbeirosRoute
  '/_authenticated/app/clientes': typeof AuthenticatedAppClientesRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/financeiro': typeof AuthenticatedAppFinanceiroRoute
  '/_authenticated/app/servicos': typeof AuthenticatedAppServicosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/b/$slug'
    | '/app/agenda'
    | '/app/barbeiros'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/financeiro'
    | '/app/servicos'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/b/$slug'
    | '/app/agenda'
    | '/app/barbeiros'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/financeiro'
    | '/app/servicos'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/b/$slug'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/barbeiros'
    | '/_authenticated/app/clientes'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/financeiro'
    | '/_authenticated/app/servicos'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  BSlugRoute: typeof BSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$slug': {
      id: '/b/$slug'
      path: '/b/$slug'
      fullPath: '/b/$slug'
      preLoaderRoute: typeof BSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/servicos': {
      id: '/_authenticated/app/servicos'
      path: '/app/servicos'
      fullPath: '/app/servicos'
      preLoaderRoute: typeof AuthenticatedAppServicosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/financeiro': {
      id: '/_authenticated/app/financeiro'
      path: '/app/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AuthenticatedAppFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/app/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/clientes': {
      id: '/_authenticated/app/clientes'
      path: '/app/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AuthenticatedAppClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/barbeiros': {
      id: '/_authenticated/app/barbeiros'
      path: '/app/barbeiros'
      fullPath: '/app/barbeiros'
      preLoaderRoute: typeof AuthenticatedAppBarbeirosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/app/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppBarbeirosRoute: typeof AuthenticatedAppBarbeirosRoute
  AuthenticatedAppClientesRoute: typeof AuthenticatedAppClientesRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppFinanceiroRoute: typeof AuthenticatedAppFinanceiroRoute
  AuthenticatedAppServicosRoute: typeof AuthenticatedAppServicosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppBarbeirosRoute: AuthenticatedAppBarbeirosRoute,
  AuthenticatedAppClientesRoute: AuthenticatedAppClientesRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppFinanceiroRoute: AuthenticatedAppFinanceiroRoute,
  AuthenticatedAppServicosRoute: AuthenticatedAppServicosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  BSlugRoute: BSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
